### ISSUE TITLE
Crotal broken after update from 0.6.0 to 0.9.7

### ISSUE THREAD

**Issue by crsqq** [dinever/crotal#18]
Updated crotal, now it doesn't work anymore.
Why:
There are not "tags: " entries in my post source files. That wasn't a problem in version 0.6.
But with the most recent version, site generation doesn't work any more.
If I run the generate command, the I get an attribute error:

```python
Traceback (most recent call last):
  File "/home/user/venvs/blog/bin/crotal", line 9, in <module>
    load_entry_point('crotal==0.9.7', 'console_scripts', 'crotal')()
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/main.py", line 66, in main
    func(**vars(args))
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/command.py", line 74, in generate
    site = Site(path=utils.locate_base_dir(), full=full, output=output)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/site.py", line 33, in __init__
    model.load(self.database, self.config, self.update_data)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 110, in load
    cls.load_main_items(config)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 130, in load_main_items
    obj = cls.load_single_file(file_path, config)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 152, in load_single_file
    item = cls.from_file(file_path, config)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 164, in from_file
    return cls.parse_content(file_path, content, config)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 186, in parse_content
    return cls(**attributes)
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/base.py", line 86, in __init__
    self.create()
  File "/home/user/venvs/blog/local/lib/python2.7/site-packages/crotal/models/post.py", line 106, in create
    self.tags = [Tag.add(item, self) for item in self.raw_tags]
AttributeError: 'Post' object has no attribute 'raw_tags'
```

**Comment by dinever** [comment]
Hi Chris,

Sorry for the bug. Now I have fixed the attribute error and published a newer version `0.9.8`. Please update crotal and try again.

Please notice that crotal has changed the template engine from `Jinja2` to `Mako` due to performance. So the template you used in `0.6.0` may not be working anymore.

However, you can create a new site using the newer version crotal, and move your posts into the newer site folder.

```
crotal init new_site
```

Move the posts into the newer site folder.

```
cp -rf old_site/source/* new_site/source/
```

Generate the site.

```
cd new_site
crotal generate -f
crotal server
```

Also, please notice that the port number has changed from `8000` to `1124` due to conflicts with other service. However, you can change the port manually by this:

```
crotal server -p 8088
```

Thank you for your interest in this project and wish you a pleasant day!

Ding

**Comment by crsqq** [comment]
Dear Ding,

site generation works fine with the new version (0.98). Thank you so much for the quick response and the bug fix!
But as you supposed: my old template is broken. However, the new default template looks fine, too! Gotta adjust this over the weekend.. :)

Regards,
Chris.
